add fixed

diff --git a/.github/workflows/coq.yml b/.github/workflows/coq.yml
--- a/.github/workflows/coq.yml
+++ b/.github/workflows/coq.yml
@@ -14,12 +14,11 @@ jobs:
       - uses: actions/checkout@v4
       - name: Show Coq version
         run: coqc -v
-      - name: Build FLT-new.v
+      - name: Build FLT-new.v (Track B GN2)
         run: coqc FLT-new.v
-      - name: Build FLT-old.v
+      - name: Build FLT-old.v (Track A Coverage)
         run: coqc FLT-old.v
       - name: Fail if any Admitted remain
         run: |
           if grep -R -n --include="*.v" 'Admitted\.' .; then
-            echo "::error ::Found Admitted."; exit 1; fi
-
+            echo "::error::Found Admitted"; exit 1; fi
